import { PaymentRecord } from './payment-types'

// export const paymentRecords: PaymentRecord[] = [
//   {
//     id: "STU001",
//     name: "JohnDoe",
//     activity: "Swimming",
//     category: "Sports",
//     courseType: "Regular",
//     finalPayment: 12000,
//     totalPaidAmount: 12000,
//     balancePayment: 0,
//     paymentStatus: "Paid",
//     paymentFrequency: "Yearly",
//     nextPaymentDate: "2025-01-15",
//     paidDate: "2024-01-15",
//     paymentReminder: false,
//     reminderMode: "SMS",
//     communicationText: "Thank you John for completing your yearly payment. Enjoy your swimming classes!",
//     paymentDetails: {
//       upiId: "john@upi",
//       paymentLink: "https://pay.academy.com/john001",
//     },
//     currency: "USD",
//     emiSplit: 4,
//     reminderDays: [],
//     registrationFees: {
//       studentRegistration: 500,
//       courseRegistration: 300,
//       confirmationFee: 1000,
//       paid: true,
//     },
//     paymentModes: ["UPI", "Card"],
//     studentType: "New",
//   },
//   {
//     id: "STU002",
//     name: "Priya Sharma",
//     activity: "Classical Dance",
//     category: "Arts",
//     courseType: "Special",
//     finalPayment: 2500,
//     totalPaidAmount: 2500,
//     balancePayment: 0,
//     paymentStatus: "Paid",
//     paymentFrequency: "Monthly",
//     nextPaymentDate: "2024-02-01",
//     paidDate: "2024-01-01",
//     paymentReminder: true,
//     reminderMode: "Email",
//     communicationText: "Thank you Priya for your payment. Your next monthly payment is due on Feb 1st.",
//     paymentDetails: {
//       qrCode: "QR_CODE_PRIYA",
//       upiId: "priya@paytm",
//       paymentLink: "https://pay.academy.com/priya002",
//     },
//     currency: "INR",
//     reminderDays: [7, 4, 2],
//     registrationFees: {
//       studentRegistration: 200,
//       courseRegistration: 150,
//       confirmationFee: 500,
//       paid: true,
//     },
//     paymentModes: ["QR", "UPI"],
//     studentType: "Existing",
//   },
//   {
//     id: "STU003",
//     name: "Emma Wilson",
//     activity: "Piano",
//     category: "Music",
//     courseType: "Ongoing",
//     finalPayment: 3500,
//     totalPaidAmount: 0,
//     balancePayment: 3500,
//     paymentStatus: "Pending",
//     paymentFrequency: "Weekly",
//     nextPaymentDate: "2024-01-20",
//     paidDate: "",
//     paymentReminder: true,
//     reminderMode: "WhatsApp",
//     communicationText: "Hi Emma, your weekly payment of $875 is pending. Please complete payment to start classes.",
//     paymentDetails: {
//       qrCode: "QR_CODE_EMMA",
//       upiId: "emma@gpay",
//       paymentLink: "https://pay.academy.com/emma003",
//     },
//     currency: "USD",
//     reminderDays: [2, 1],
//     paymentModes: ["Link", "QR"],
//     studentType: "New",
//   },
//   {
//     id: "STU004",
//     name: "Raj Patel",
//     activity: "Football",
//     category: "Sports",
//     courseType: "Regular",
//     finalPayment: 8000,
//     totalPaidAmount: 6000,
//     balancePayment: 2000,
//     paymentStatus: "Overdue",
//     paymentFrequency: "Yearly",
//     nextPaymentDate: "2024-01-18",
//     paidDate: "2024-01-01",
//     paymentReminder: true,
//     reminderMode: "SMS",
//     communicationText: "URGENT: Raj, your EMI payment is overdue. Please pay $2000 immediately to avoid suspension.",
//     paymentDetails: {
//       upiId: "raj@gpay",
//       paymentLink: "https://pay.academy.com/raj004",
//     },
//     currency: "INR",
//     emiSplit: 4,
//     reminderDays: [30, 10, 5, 2, 1],
//     registrationFees: {
//       studentRegistration: 400,
//       paid: true,
//     },
//     paymentModes: ["UPI", "Link"],
//     studentType: "Existing",
//   },
//   {
//     id: "STU005",
//     name: "Sarah Johnson",
//     activity: "Painting",
//     category: "Arts",
//     courseType: "Special",
//     finalPayment: 4000,
//     totalPaidAmount: 4000,
//     balancePayment: 0,
//     paymentStatus: "Paid",
//     paymentFrequency: "One-time",
//     nextPaymentDate: "-",
//     paidDate: "2024-01-05",
//     paymentReminder: false,
//     reminderMode: "Email",
//     communicationText: "Payment completed successfully Sarah. Enjoy your painting classes!",
//     paymentDetails: {
//       qrCode: "QR_CODE_SARAH",
//       paymentLink: "https://pay.academy.com/sarah005",
//     },
//     currency: "USD",
//     reminderDays: [],
//     paymentModes: ["QR", "Link"],
//     studentType: "New",
//   },
//   {
//     id: "STU006",
//     name: "Mike Chen",
//     activity: "Guitar",
//     category: "Music",
//     courseType: "Regular",
//     finalPayment: 1800,
//     totalPaidAmount: 1200,
//     balancePayment: 600,
//     paymentStatus: "Partial",
//     paymentFrequency: "Monthly",
//     nextPaymentDate: "2024-02-10",
//     paidDate: "2024-01-10",
//     paymentReminder: true,
//     reminderMode: "WhatsApp",
//     communicationText: "Hi Mike, you have paid $1200. Balance amount $600 is due on Feb 10th.",
//     paymentDetails: {
//       qrCode: "QR_CODE_MIKE",
//       upiId: "mike@upi",
//       paymentLink: "https://pay.academy.com/mike006",
//     },
//     currency: "USD",
//     reminderDays: [7, 4, 2],
//     paymentModes: ["UPI", "QR"],
//     studentType: "Existing",
//   },
//   {
//     id: "STU007",
//     name: "Lisa Wang",
//     activity: "Swimming",
//     category: "Sports",
//     courseType: "Regular",
//     finalPayment: 11000,
//     totalPaidAmount: 9000,
//     balancePayment: 2000,
//     paymentStatus: "Partial",
//     paymentFrequency: "Yearly",
//     nextPaymentDate: "2024-03-15",
//     paidDate: "2024-01-15",
//     paymentReminder: true,
//     reminderMode: "Email",
//     communicationText: "Hi Lisa, your next EMI payment of $2000 is due on March 15th.",
//     paymentDetails: {
//       qrCode: "QR_CODE_LISA",
//       upiId: "lisa@upi",
//       paymentLink: "https://pay.academy.com/lisa007",
//     },
//     currency: "USD",
//     emiSplit: 4,
//     reminderDays: [30, 10, 5, 2, 1],
//     registrationFees: {
//       confirmationFee: 1000,
//       paid: true,
//     },
//     paymentModes: ["QR", "UPI", "Link"],
//     studentType: "Existing",
//   },
//   {
//     id: "STU008",
//     name: "David Kumar",
//     activity: "Classical Dance",
//     category: "Arts",
//     courseType: "Special",
//     finalPayment: 2500,
//     totalPaidAmount: 2500,
//     balancePayment: 0,
//     paymentStatus: "Paid",
//     paymentFrequency: "Monthly",
//     nextPaymentDate: "2024-02-15",
//     paidDate: "2024-01-15",
//     paymentReminder: true,
//     reminderMode: "SMS",
//     communicationText: "Thank you David for your payment. Next payment due on Feb 15th.",
//     paymentDetails: {
//       upiId: "david@upi",
//       paymentLink: "https://pay.academy.com/david008",
//     },
//     currency: "INR",
//     reminderDays: [7, 4, 2],
//     paymentModes: ["UPI", "Link"],
//     studentType: "New",
//   },
//   {
//      id: "STU009",
//     name: "Nithya",
//     activity: "Swimming",
//     category: "Sports",
//     courseType: "Regular",
//     finalPayment: 12000,
//     totalPaidAmount: 12000,
//     balancePayment: 0,
//     paymentStatus: "Paid",
//     paymentFrequency: "Yearly",
//     nextPaymentDate: "2025-01-15",
//     paidDate: "2024-01-15",
//     paymentReminder: false,
//     reminderMode: "SMS",
//     communicationText: "Thank you John for completing your yearly payment. Enjoy your swimming classes!",
//     paymentDetails: {
//       upiId: "john@upi",
//       paymentLink: "https://pay.academy.com/john001",
//     },
//     currency: "USD",
//     emiSplit: 4,
//     reminderDays: [],
//     registrationFees: {
//       studentRegistration: 500,
//       courseRegistration: 300,
//       confirmationFee: 1000,
//       paid: true,
//     },
//     paymentModes: ["UPI", "Card"],
//     studentType: "New",
//   },
// ]

export const courseWisePayments = [
  { course: "Swimming", amount: 23000, students: 2, received: 21000, outstanding: 2000 },
  { course: "Classical Dance", amount: 5000, students: 2, received: 5000, outstanding: 0 },
  { course: "Piano", amount: 3500, students: 1, received: 0, outstanding: 3500 },
  { course: "Football", amount: 8000, students: 1, received: 6000, outstanding: 2000 },
  { course: "Painting", amount: 4000, students: 1, received: 4000, outstanding: 0 },
  { course: "Guitar", amount: 1800, students: 1, received: 1200, outstanding: 600 },
]